config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipes#index'
  get '/login', to: 'session#new'
  get '/seed', to: 'seed#index'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  delete '/favorites', to: 'favorites#destroy'

  resources :categories, only: [:index, :new, :create, :show]
  resources :recipes, only: [:index, :create, :update, :new, :show, :edit]
  resources :users, only: [:show]
  resources :favorites, only: [:new, :create]
  resources :recipe_categories, only: [:create, :new]

  namespace :api do
    namespace :v1 do
      resources :recipes, only: [:index] do

      end

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :recipe_categories
  has_many :recipes, through: :recipe_categories

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :recipe

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  validates_presence_of :name, :ingredients, :directions
  validates :name, uniqueness: true

  has_many :favorites
  has_many :recipe_categories
  has_many :categories, through: :recipe_categories

  def ingredients_list
    ingredients.split(",")
  end

  def favorite?(user_id)
    user_ids = favorites.pluck(:user_id)

    user_ids.include?(user_id)
  end

end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
  belongs_to :recipe
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord

  has_many :favorites
  has_many :recipes, through: :favorites

  has_secure_password
  enum role: %w(user admin)


end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < ApplicationController

  def index
    @recipe = Recipe.all
    render json:@recipe
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :current_admin?

  def current_user
    @current_user_lookup ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params)
    if category.save
      redirect_to categories_path
    else
      redirect_to "/categories/new"
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def new

  end


  def create

    favorite = Favorite.new(recipe_id: params[:recipe_id].to_i, user_id: current_user.id)
    # Also need to add uniqueness to Favorites.  Also reconsider redirects.
    if favorite.save
      redirect_to "/recipes"
    else
      redirect_to "/recipes/#{favorite_params[:recipe_id]}"
      flash[:warning] = "Invalid entry"
    end
  end

  def destroy
    favorite_id =Favorite.where(user_id: current_user.id, recipe_id: params['recipe_id']).pluck(:id)
    favorite = Favorite.find(favorite_id[0])
    favorite.delete
    redirect_back(fallback_location: root_path)
  end

  private

  def favorite_params
    params.require(:favorite).permit(:user_id, :recipe_id)
  end

end

app/controllers/recipe_categories_controller.rb
class RecipeCategoriesController < ApplicationController

  def new

  end

  def create
    recipe_id = params[:recipe_id].to_i
    category_id = Category.find_by(name: params[:category_name]).id
    if RecipeCategory.where(recipe_id: recipe_id).find_by(category_id: category_id) == nil
      RecipeCategory.create(recipe_id: recipe_id, category_id: category_id)
      redirect_to "/recipes/#{recipe_id}/edit"
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def new
    if current_admin?
      @recipe = Recipe.new
    else
      redirect_to "/recipes"
    end
  end

  def edit
    if current_admin?
      @recipe = Recipe.find(params[:id])
      @categories = Category.all.pluck(:name)
      @current_categories = @recipe.categories
    else
      redirect_to "/recipes"
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :new
    end

  end

  def show
    @recipe = Recipe.find(params[:id])
    @categories = @recipe.categories
  end

  def create
    recipe = Recipe.new(recipe_params)

    if recipe.save
      redirect_to "/recipes"
    else
      redirect_to "/recipes/new"
      flash[:warning] = "Invalid entry"
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :ingredients, :directions, :notes, :gif, :video, :link)
  end

end

app/controllers/seed_controller.rb
class SeedController < ApplicationController

  def index
    recipes = Recipe.all
    render json: RecipeSerializer.new(recipes)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new

  end

  def create
    user = User.find_by(name: params[:name])
     if user && user.authenticate(params[:password])
       session[:user_id] = user.id
       redirect_to root_path
     else
       flash[:warning] = "Invalid entry"
       render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if current_user.id != params[:id].to_i
    redirect_to root_path
    end
    @user = current_user
    @favorites = @user.recipes
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h1> Categories </h1>

<%if current_admin?%>
  <%= button_to "New Category", new_category_path, method: :get%>
<%end%>

<ul>
  <% @categories.each do |category| %>
    <li><a href="categories/<%=category.id%>"><%=category.name  %></a></li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<%end%>

app/views/categories/show.html.erb
<h1> <%= @category.name %> </h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li><a href="../recipes/<%=recipe.id%>"><%=recipe.name  %></a></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PbrBeta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "/partials/nav" %>
    <%= yield %>
  </body>
  <footer style="height:100px;" />
</html>

app/views/partials/_nav.html.erb
<div style="height:50px;"> </div>
<div class="navbar">
  <h1>Plant Based Recipes</h1>
  <div class="btn-group">
    <div >
      <%= button_to "Recipes", recipes_path, method: :get %>
    </div>
    <div>
      <%= button_to "Categories", categories_path, method: :get %>
    </div>
    <div>
      <%if current_user == nil%>
        <%= button_to "Sign In", login_path %>
      <%else%>
        <%= button_to "Log Out" , logout_path, method: :delete %>
      <%end%>
    </div>
    <div>
      <% if current_user != nil%>
        <%= button_to "Home", user_path(current_user), method: :get %>
      <%end%>
    </div>
  </div>
</div>

app/views/recipes/_form.html.erb
<div class="section">
  <%= form_for @recipe do |r| %>
    <div class="recipe-field">
     <%= r.label :name, "Name" %>
     <%= r.text_field :name %>
    </div>
    <div class="recipe-field">
     <%= r.label :ingredients, "Ingredients" %>
     <%= r.text_area :ingredients %>
    </div>
    <div class="recipe-field">
     <%= r.label :directions, "Directions"%>
     <%= r.text_area :directions %>
    </div>
    <div class="recipe-field">
     <%= r.label :notes, "Notes"%>
     <%= r.text_area :notes %>
    </div>
    <div class="recipe-field">
     <%= r.label :gif, "Gif" %>
     <%= r.text_field :gif %>
    </div>
    <div class="recipe-field">
     <%= r.label :video, "Video" %>
     <%= r.text_field :video %>
    </div>
    <div class="recipe-field">
     <%= r.label :link, "Link" %>
     <%= r.text_field :link %>
    </div>
     <%= r.submit  %>
   <%end%>
</div>

app/views/recipes/edit.html.erb
<h1>Edit <%=@recipe.name%> </h1>

<%= render 'form' %>

<div class="section">
  <h2> Current Categories</h2>
  <ul><% @current_categories.each do |category| %>
    <li><%= category.name%></li>
    <% end %>
  </ul>
  <h2> Add a Category to this recipe</h2>
  <%= form_tag(recipe_categories_path(:recipe_id => @recipe.id), :method => "post") do %>
   <%= select_tag "category_name", options_for_select(@categories) %>
   <%= submit_tag "Add Category" %>
  <%end%>
</div>

app/views/recipes/index.html.erb
<h1> Recipes </h1>

<%if current_admin?%>
  <%= button_to "New Recipe", new_recipe_path, method: :get%>
<%end%>

<ul>
  <% @recipes.each do |recipe| %>
    <li><a href="recipes/<%=recipe.id%>"><%=recipe.name  %></a></li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<div>
<h1><%= @recipe.name %> </h1>
<ul><% @categories.each do |category| %>
  <li><%= category.name%></li>
  <% end %>
</ul>
<br/>
<% if current_user != nil && @recipe.favorite?(current_user.id)  == false %>
  <%= button_to "Add to Favorites", favorites_path, params: {recipe_id: params[:id]} %>
<%end%>
<%if current_admin?%>
  <%= button_to "Edit", edit_recipe_path(@recipe), method: :get %>
<%end%>
</div>

<p>
  <h2> Ingredients </h2>
  <ul><% @recipe.ingredients_list.each do |ingredient| %>
    <li><%= ingredient%></li>
    <% end %>
  </ul>
</p>
<p>
  <h2> Directions </h2>
  <%= @recipe.directions %> </p>

<p>
  <h2> Notes </h2>
  <%= @recipe.notes %> </p>

app/views/session/new.html.erb
<h1>Login</h1>

<%= form_tag login_path do %>
  <p><%= label_tag :name %>
  <%= text_field_tag :name %></p>
  <p><%= label_tag :password %>
  <%= password_field_tag :password %></p>
  <%= submit_tag 'Login' %>
<% end %>

app/views/users/show.html.erb
<h1> Welcome <%= @user.name %> </h1>

<h2> Favorites </h2>

<ul>
  <% @favorites.each do |favorite| %>
    <li><a href="/recipes/<%=favorite.id%>"><%=favorite.name  %></a> <%= button_to "Remove Favorite", favorites_path(favorite), method: :delete, params: {recipe_id: favorite.id} %></li>
  <% end %>
</ul>